spring:
  cloud:
    config:
      server:
        git:
          uri: /home/a/IdeaProjects/microservice-store
          search-paths: git-config
  application:
    name: config-server
server:
  port: 8901
